FROM nicocartalla/altoromutual:latest

RUN apt update && apt-get install -y python3 python3-pip && pip3 install requests
WORKDIR /dast
COPY dast .
COPY dast-entrypoint.sh /dast-entrypoint.sh
RUN chmod +x /dast-entrypoint.sh
CMD ["/dast-entrypoint.sh"]

