# Etapa de build
FROM openjdk:17-buster as build
RUN apt-get update && apt-get install -y \
    curl unzip \
    && rm -rf /var/lib/apt/lists/*
ENV GRADLE_VERSION=8.4
RUN curl -L https://services.gradle.org/distributions/gradle-$GRADLE_VERSION-bin.zip -o gradle-$GRADLE_VERSION-bin.zip \
    && unzip gradle-${GRADLE_VERSION}-bin.zip \
    && rm -f gradle-${GRADLE_VERSION}-bin.zip
ENV PATH=$PATH:/gradle-${GRADLE_VERSION}/bin
ENV GRADLE_USER_HOME /cache
WORKDIR /app
COPY . /app
RUN gradle clean build
COPY sast-entrypoint.sh /sast-entrypoint.sh
RUN chmod +x /sast-entrypoint.sh
CMD ["/sast-entrypoint.sh"]