name: Altoro CI

on:
  pull_request:
    branches: [ main ]

jobs:
  validate-pr:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install docker
      run: |
        sudo apt update
        sudo apt install apt-transport-https ca-certificates curl software-properties-common
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable" && sudo apt update
        apt-cache policy docker-ce
        sudo apt install docker-ce

    - name: docker login
      run: |
        echo ${{ secrets.DOCKER_TOKEN }} | docker login -u nicocartalla --password-stdin

    - name: Build image
      run: |
        docker build -t nicocartalla/altoromutual:latest .

    - name: Tag image with commit ID
      run: |
        docker tag nicocartalla/altoromutual:latest nicocartalla/altoromutual:${{ github.sha }}

    - name: Run DAST test
      run: |
        docker build -t dast-test-altoro -f Dockerfile-dast .
        docker run dast-test-altoro

    - name: Run SAST test and push to SonarCloud
      run: |
        docker build -t sast-test-altoro -f Dockerfile-sast .
        docker run -e SONAR_PROJECT_KEY=altoro  -e SONAR_PROJECT=altoro -e SONAR_TOKEN=${{ secrets.SONAR_TOKEN }} -e SONAR_URL=${{ secrets.SONAR_TOKEN }} sast-test-altoro

    - name: Push image tags to Docker Hub
      run: |
        docker push nicocartalla/altoromutual:latest
        docker push nicocartalla/altoromutual:${{ github.sha }}