name: Altoro CI

env:
  REPO: ${{ github.repository }}
  REGISTRY: ghcr.io

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: image env in lower case
        run: |
          echo "IMAGE_NAME=$(echo $REGISTRY/$REPO | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}

  validate-pr:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install docker
      run: |
        sudo apt update
        sudo apt install apt-transport-https ca-certificates curl software-properties-common
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable" && sudo apt update
        apt-cache policy docker-ce
        sudo apt install docker-ce

    - name: print variables
      run: |
        echo ${{ env.IMAGE_NAME }}
        echo ${{ github.event.pull_request.head.sha }}

    - name: Build image
      run: |
        docker build -t nicocartalla/altoromutual:latest .

    - name: Run DAST test
      run: |
        docker build -t dast-test-altoro -f Dockerfile-dast .
        docker run dast-test-altoro
