name: DAST

on:
  pull_request:
    branches: [ main ]

jobs:
  validate-pr:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install docker
      run: |
        sudo apt update
        sudo apt install apt-transport-https ca-certificates curl software-properties-common
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable" && sudo apt update
        apt-cache policy docker-ce
        sudo apt install docker-ce

    - name: Build image
      run: |
        docker build -t nicocartalla/altoromutual:latest .

    - name: Run DAST test
      run: |
        docker build -t dast-test-altoro -f Dockerfile-dast .
        docker run dast-test-altoro
